import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./main.scss";
import Sidebar from "@/components/core/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="core-layout">
          <div className="sidebar">
            <Sidebar />
          </div>
          <div className="columns-layout">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
